In [1]:
from torch_geometric.loader import DataLoader
import torch
import numpy as np
import pandas as pd

/data/conghao001/anaconda3/envs/gnndrug/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
from utils_data import TestbedDataset

In [3]:
device = torch.device("cuda:0")
# device = torch.device("cpu")
device

device(type='cuda', index=0)

In [6]:
from models import GATNet_E, GATNet, GCNNet
model = GATNet()
model_path = 'root_folder/root_006/models/model_GAT-EP300-SW801010_GDSC.model'

# model = GCNNet()
# model_path = 'root_folder/root_006/models/model_GCN-EP300-SW801010_GDSC.model'

# both state dict and model need to be moved to cuda manually 
model.load_state_dict(torch.load(model_path, map_location=device))
model.to(device)

GATNet(
  (gcn1): GATConv(270, 270, heads=10)
  (gcn2): GATConv(2700, 128, heads=1)
  (fc_g1): Linear(in_features=128, out_features=128, bias=True)
  (conv_xt_1): Conv1d(1, 32, kernel_size=(8,), stride=(1,))
  (pool_xt_1): MaxPool1d(kernel_size=3, stride=3, padding=0, dilation=1, ceil_mode=False)
  (conv_xt_2): Conv1d(32, 64, kernel_size=(8,), stride=(1,))
  (pool_xt_2): MaxPool1d(kernel_size=3, stride=3, padding=0, dilation=1, ceil_mode=False)
  (conv_xt_3): Conv1d(64, 128, kernel_size=(8,), stride=(1,))
  (pool_xt_3): MaxPool1d(kernel_size=3, stride=3, padding=0, dilation=1, ceil_mode=False)
  (fc1_xt): Linear(in_features=2944, out_features=128, bias=True)
  (fc1): Linear(in_features=256, out_features=1024, bias=True)
  (fc2): Linear(in_features=1024, out_features=128, bias=True)
  (out): Linear(in_features=128, out_features=1, bias=True)
  (relu): ReLU()
  (dropout): Dropout(p=0.5, inplace=False)
)

In [7]:
branch_folder = "root_folder/root_006"
dataset = 'GDSC'
test_data = TestbedDataset(root=branch_folder, dataset=dataset+'_test_mix')

Pre-processed data found: root_folder/root_006/processed/GDSC_test_mix.pt, loading ...


In [8]:
test_data.data

Data(x=[153927, 270], edge_index=[2, 339598], y=[4827], edge_features=[339598, 4], smiles=[4827], drug_name=[4827], cell_line_name=[4827], target=[4827, 735], c_size=[4827])

In [9]:
test_data.slices

defaultdict(dict,
            {'x': tensor([     0,     28,     63,  ..., 153867, 153897, 153927]),
             'edge_index': tensor([     0,     62,    142,  ..., 339458, 339528, 339598]),
             'y': tensor([   0,    1,    2,  ..., 4825, 4826, 4827]),
             'edge_features': tensor([     0,     62,    142,  ..., 339458, 339528, 339598]),
             'smiles': tensor([   0,    1,    2,  ..., 4825, 4826, 4827]),
             'drug_name': tensor([   0,    1,    2,  ..., 4825, 4826, 4827]),
             'cell_line_name': tensor([   0,    1,    2,  ..., 4825, 4826, 4827]),
             'target': tensor([   0,    1,    2,  ..., 4825, 4826, 4827]),
             'c_size': tensor([   0,    1,    2,  ..., 4825, 4826, 4827])})

In [10]:
test_batch = 1
test_loader = DataLoader(test_data, batch_size=test_batch, shuffle=False)

In [11]:
len(test_loader.dataset)

4827

In [74]:
for data in test_loader:
#     x, target, edge_index, batch, edge_feat = data.x, data.target, data.edge_index, data.batch, data.edge_features
    output, _ = model(data.x, data.target, data.edge_index, data.batch, data.edge_features)
    print(output)

tensor([[0.3573],
        [0.6219],
        [0.5696],
        ...,
        [0.4879],
        [0.5266],
        [0.5885]], grad_fn=<SigmoidBackward>)
tensor([[0.6076],
        [0.6259],
        [0.5285],
        ...,
        [0.5550],
        [0.5575],
        [0.5986]], grad_fn=<SigmoidBackward>)
tensor([[0.5641],
        [0.4097],
        [0.5570],
        ...,
        [0.5282],
        [0.5880],
        [0.4597]], grad_fn=<SigmoidBackward>)
tensor([[0.5695],
        [0.5901],
        [0.5771],
        ...,
        [0.5975],
        [0.5866],
        [0.5663]], grad_fn=<SigmoidBackward>)
tensor([[0.6478],
        [0.5992],
        [0.5523],
        [0.4410],
        [0.6038],
        [0.6681],
        [0.4520],
        [0.5714],
        [0.3669],
        [0.5095],
        [0.5971],
        [0.5285],
        [0.5404],
        [0.4983],
        [0.5405],
        [0.5485],
        [0.5536],
        [0.5716],
        [0.5951],
        [0.4758],
        [0.3655],
        [0.4699],
        

In [15]:
for data in test_loader:
    print(data)

DataBatch(x=[28, 270], edge_index=[2, 62], y=[1], edge_features=[62, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[28], ptr=[2])
DataBatch(x=[35, 270], edge_index=[2, 80], y=[1], edge_features=[80, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[35], ptr=[2])
DataBatch(x=[44, 270], edge_index=[2, 100], y=[1], edge_features=[100, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[44], ptr=[2])
DataBatch(x=[34, 270], edge_index=[2, 74], y=[1], edge_features=[74, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[34], ptr=[2])
DataBatch(x=[24, 270], edge_index=[2, 54], y=[1], edge_features=[54, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[24], ptr=[2])
DataBatch(x=[32, 270], edge_index=[2, 72], y=[1], edge_features=[72, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1],

DataBatch(x=[31, 270], edge_index=[2, 68], y=[1], edge_features=[68, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[31], ptr=[2])
DataBatch(x=[30, 270], edge_index=[2, 70], y=[1], edge_features=[70, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[30], ptr=[2])
DataBatch(x=[32, 270], edge_index=[2, 72], y=[1], edge_features=[72, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[32], ptr=[2])
DataBatch(x=[28, 270], edge_index=[2, 60], y=[1], edge_features=[60, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[28], ptr=[2])
DataBatch(x=[9, 270], edge_index=[2, 18], y=[1], edge_features=[18, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[9], ptr=[2])
DataBatch(x=[24, 270], edge_index=[2, 52], y=[1], edge_features=[52, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], bat

DataBatch(x=[34, 270], edge_index=[2, 74], y=[1], edge_features=[74, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[34], ptr=[2])
DataBatch(x=[35, 270], edge_index=[2, 80], y=[1], edge_features=[80, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[35], ptr=[2])
DataBatch(x=[74, 270], edge_index=[2, 162], y=[1], edge_features=[162, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[74], ptr=[2])
DataBatch(x=[28, 270], edge_index=[2, 60], y=[1], edge_features=[60, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[28], ptr=[2])
DataBatch(x=[74, 270], edge_index=[2, 162], y=[1], edge_features=[162, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[74], ptr=[2])
DataBatch(x=[26, 270], edge_index=[2, 60], y=[1], edge_features=[60, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1

DataBatch(x=[15, 270], edge_index=[2, 32], y=[1], edge_features=[32, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[15], ptr=[2])
DataBatch(x=[28, 270], edge_index=[2, 60], y=[1], edge_features=[60, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[28], ptr=[2])
DataBatch(x=[30, 270], edge_index=[2, 66], y=[1], edge_features=[66, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[30], ptr=[2])
DataBatch(x=[30, 270], edge_index=[2, 66], y=[1], edge_features=[66, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[30], ptr=[2])
DataBatch(x=[30, 270], edge_index=[2, 66], y=[1], edge_features=[66, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[30], ptr=[2])
DataBatch(x=[61, 270], edge_index=[2, 136], y=[1], edge_features=[136, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1],

DataBatch(x=[14, 270], edge_index=[2, 30], y=[1], edge_features=[30, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[14], ptr=[2])
DataBatch(x=[15, 270], edge_index=[2, 32], y=[1], edge_features=[32, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[15], ptr=[2])
DataBatch(x=[28, 270], edge_index=[2, 62], y=[1], edge_features=[62, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[28], ptr=[2])
DataBatch(x=[30, 270], edge_index=[2, 70], y=[1], edge_features=[70, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[30], ptr=[2])
DataBatch(x=[18, 270], edge_index=[2, 38], y=[1], edge_features=[38, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[18], ptr=[2])
DataBatch(x=[30, 270], edge_index=[2, 66], y=[1], edge_features=[66, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], b

DataBatch(x=[30, 270], edge_index=[2, 66], y=[1], edge_features=[66, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[30], ptr=[2])
DataBatch(x=[31, 270], edge_index=[2, 68], y=[1], edge_features=[68, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[31], ptr=[2])
DataBatch(x=[32, 270], edge_index=[2, 72], y=[1], edge_features=[72, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[32], ptr=[2])
DataBatch(x=[30, 270], edge_index=[2, 68], y=[1], edge_features=[68, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[30], ptr=[2])
DataBatch(x=[32, 270], edge_index=[2, 72], y=[1], edge_features=[72, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[32], ptr=[2])
DataBatch(x=[30, 270], edge_index=[2, 66], y=[1], edge_features=[66, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], b

DataBatch(x=[30, 270], edge_index=[2, 66], y=[1], edge_features=[66, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[30], ptr=[2])
DataBatch(x=[33, 270], edge_index=[2, 72], y=[1], edge_features=[72, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[33], ptr=[2])
DataBatch(x=[58, 270], edge_index=[2, 126], y=[1], edge_features=[126, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[58], ptr=[2])
DataBatch(x=[24, 270], edge_index=[2, 52], y=[1], edge_features=[52, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[24], ptr=[2])
DataBatch(x=[28, 270], edge_index=[2, 62], y=[1], edge_features=[62, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[28], ptr=[2])
DataBatch(x=[74, 270], edge_index=[2, 162], y=[1], edge_features=[162, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1

DataBatch(x=[27, 270], edge_index=[2, 62], y=[1], edge_features=[62, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[27], ptr=[2])
DataBatch(x=[28, 270], edge_index=[2, 60], y=[1], edge_features=[60, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[28], ptr=[2])
DataBatch(x=[28, 270], edge_index=[2, 64], y=[1], edge_features=[64, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[28], ptr=[2])
DataBatch(x=[35, 270], edge_index=[2, 76], y=[1], edge_features=[76, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[35], ptr=[2])
DataBatch(x=[19, 270], edge_index=[2, 38], y=[1], edge_features=[38, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[19], ptr=[2])
DataBatch(x=[32, 270], edge_index=[2, 72], y=[1], edge_features=[72, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], b

DataBatch(x=[24, 270], edge_index=[2, 52], y=[1], edge_features=[52, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[24], ptr=[2])
DataBatch(x=[37, 270], edge_index=[2, 82], y=[1], edge_features=[82, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[37], ptr=[2])
DataBatch(x=[14, 270], edge_index=[2, 28], y=[1], edge_features=[28, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[14], ptr=[2])
DataBatch(x=[37, 270], edge_index=[2, 82], y=[1], edge_features=[82, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[37], ptr=[2])
DataBatch(x=[38, 270], edge_index=[2, 86], y=[1], edge_features=[86, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[38], ptr=[2])
DataBatch(x=[32, 270], edge_index=[2, 72], y=[1], edge_features=[72, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], b

DataBatch(x=[14, 270], edge_index=[2, 30], y=[1], edge_features=[30, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[14], ptr=[2])
DataBatch(x=[30, 270], edge_index=[2, 70], y=[1], edge_features=[70, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[30], ptr=[2])
DataBatch(x=[62, 270], edge_index=[2, 136], y=[1], edge_features=[136, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[62], ptr=[2])
DataBatch(x=[20, 270], edge_index=[2, 42], y=[1], edge_features=[42, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[20], ptr=[2])
DataBatch(x=[38, 270], edge_index=[2, 86], y=[1], edge_features=[86, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[38], ptr=[2])
DataBatch(x=[35, 270], edge_index=[2, 80], y=[1], edge_features=[80, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1],

DataBatch(x=[38, 270], edge_index=[2, 86], y=[1], edge_features=[86, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[38], ptr=[2])
DataBatch(x=[58, 270], edge_index=[2, 126], y=[1], edge_features=[126, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[58], ptr=[2])
DataBatch(x=[38, 270], edge_index=[2, 84], y=[1], edge_features=[84, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[38], ptr=[2])
DataBatch(x=[33, 270], edge_index=[2, 72], y=[1], edge_features=[72, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[33], ptr=[2])
DataBatch(x=[25, 270], edge_index=[2, 54], y=[1], edge_features=[54, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[25], ptr=[2])
DataBatch(x=[19, 270], edge_index=[2, 38], y=[1], edge_features=[38, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1],

DataBatch(x=[19, 270], edge_index=[2, 38], y=[1], edge_features=[38, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[19], ptr=[2])
DataBatch(x=[14, 270], edge_index=[2, 28], y=[1], edge_features=[28, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[14], ptr=[2])
DataBatch(x=[40, 270], edge_index=[2, 88], y=[1], edge_features=[88, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[40], ptr=[2])
DataBatch(x=[27, 270], edge_index=[2, 62], y=[1], edge_features=[62, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[27], ptr=[2])
DataBatch(x=[29, 270], edge_index=[2, 66], y=[1], edge_features=[66, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[29], ptr=[2])
DataBatch(x=[29, 270], edge_index=[2, 66], y=[1], edge_features=[66, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], b

DataBatch(x=[21, 270], edge_index=[2, 46], y=[1], edge_features=[46, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[21], ptr=[2])
DataBatch(x=[28, 270], edge_index=[2, 60], y=[1], edge_features=[60, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[28], ptr=[2])
DataBatch(x=[28, 270], edge_index=[2, 58], y=[1], edge_features=[58, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[28], ptr=[2])
DataBatch(x=[25, 270], edge_index=[2, 54], y=[1], edge_features=[54, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[25], ptr=[2])
DataBatch(x=[33, 270], edge_index=[2, 74], y=[1], edge_features=[74, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[33], ptr=[2])
DataBatch(x=[61, 270], edge_index=[2, 136], y=[1], edge_features=[136, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1],

DataBatch(x=[23, 270], edge_index=[2, 52], y=[1], edge_features=[52, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[23], ptr=[2])
DataBatch(x=[61, 270], edge_index=[2, 136], y=[1], edge_features=[136, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[61], ptr=[2])
DataBatch(x=[58, 270], edge_index=[2, 126], y=[1], edge_features=[126, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[58], ptr=[2])
DataBatch(x=[23, 270], edge_index=[2, 48], y=[1], edge_features=[48, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[23], ptr=[2])
DataBatch(x=[15, 270], edge_index=[2, 32], y=[1], edge_features=[32, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[15], ptr=[2])
DataBatch(x=[59, 270], edge_index=[2, 134], y=[1], edge_features=[134, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=

DataBatch(x=[58, 270], edge_index=[2, 126], y=[1], edge_features=[126, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[58], ptr=[2])
DataBatch(x=[15, 270], edge_index=[2, 32], y=[1], edge_features=[32, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[15], ptr=[2])
DataBatch(x=[37, 270], edge_index=[2, 82], y=[1], edge_features=[82, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[37], ptr=[2])
DataBatch(x=[30, 270], edge_index=[2, 70], y=[1], edge_features=[70, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[30], ptr=[2])
DataBatch(x=[23, 270], edge_index=[2, 48], y=[1], edge_features=[48, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[23], ptr=[2])
DataBatch(x=[28, 270], edge_index=[2, 60], y=[1], edge_features=[60, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1],

DataBatch(x=[33, 270], edge_index=[2, 74], y=[1], edge_features=[74, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[33], ptr=[2])
DataBatch(x=[39, 270], edge_index=[2, 86], y=[1], edge_features=[86, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[39], ptr=[2])
DataBatch(x=[34, 270], edge_index=[2, 78], y=[1], edge_features=[78, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[34], ptr=[2])
DataBatch(x=[28, 270], edge_index=[2, 60], y=[1], edge_features=[60, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[28], ptr=[2])
DataBatch(x=[34, 270], edge_index=[2, 74], y=[1], edge_features=[74, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[34], ptr=[2])
DataBatch(x=[28, 270], edge_index=[2, 62], y=[1], edge_features=[62, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], b

DataBatch(x=[23, 270], edge_index=[2, 48], y=[1], edge_features=[48, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[23], ptr=[2])
DataBatch(x=[35, 270], edge_index=[2, 80], y=[1], edge_features=[80, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[35], ptr=[2])
DataBatch(x=[74, 270], edge_index=[2, 162], y=[1], edge_features=[162, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[74], ptr=[2])
DataBatch(x=[61, 270], edge_index=[2, 136], y=[1], edge_features=[136, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[61], ptr=[2])
DataBatch(x=[21, 270], edge_index=[2, 46], y=[1], edge_features=[46, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[21], ptr=[2])
DataBatch(x=[31, 270], edge_index=[2, 68], y=[1], edge_features=[68, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1

DataBatch(x=[31, 270], edge_index=[2, 68], y=[1], edge_features=[68, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[31], ptr=[2])
DataBatch(x=[18, 270], edge_index=[2, 38], y=[1], edge_features=[38, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[18], ptr=[2])
DataBatch(x=[40, 270], edge_index=[2, 88], y=[1], edge_features=[88, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[40], ptr=[2])
DataBatch(x=[30, 270], edge_index=[2, 70], y=[1], edge_features=[70, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[30], ptr=[2])
DataBatch(x=[40, 270], edge_index=[2, 88], y=[1], edge_features=[88, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[40], ptr=[2])
DataBatch(x=[38, 270], edge_index=[2, 86], y=[1], edge_features=[86, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], b

DataBatch(x=[34, 270], edge_index=[2, 74], y=[1], edge_features=[74, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[34], ptr=[2])
DataBatch(x=[32, 270], edge_index=[2, 68], y=[1], edge_features=[68, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[32], ptr=[2])
DataBatch(x=[32, 270], edge_index=[2, 68], y=[1], edge_features=[68, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[32], ptr=[2])
DataBatch(x=[25, 270], edge_index=[2, 54], y=[1], edge_features=[54, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[25], ptr=[2])
DataBatch(x=[28, 270], edge_index=[2, 60], y=[1], edge_features=[60, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[28], ptr=[2])
DataBatch(x=[23, 270], edge_index=[2, 52], y=[1], edge_features=[52, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], b

DataBatch(x=[28, 270], edge_index=[2, 58], y=[1], edge_features=[58, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[28], ptr=[2])
DataBatch(x=[32, 270], edge_index=[2, 72], y=[1], edge_features=[72, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[32], ptr=[2])
DataBatch(x=[24, 270], edge_index=[2, 54], y=[1], edge_features=[54, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[24], ptr=[2])
DataBatch(x=[25, 270], edge_index=[2, 54], y=[1], edge_features=[54, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[25], ptr=[2])
DataBatch(x=[30, 270], edge_index=[2, 66], y=[1], edge_features=[66, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[30], ptr=[2])
DataBatch(x=[37, 270], edge_index=[2, 82], y=[1], edge_features=[82, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], b

DataBatch(x=[38, 270], edge_index=[2, 84], y=[1], edge_features=[84, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[38], ptr=[2])
DataBatch(x=[32, 270], edge_index=[2, 72], y=[1], edge_features=[72, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[32], ptr=[2])
DataBatch(x=[38, 270], edge_index=[2, 86], y=[1], edge_features=[86, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[38], ptr=[2])
DataBatch(x=[34, 270], edge_index=[2, 76], y=[1], edge_features=[76, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[34], ptr=[2])
DataBatch(x=[28, 270], edge_index=[2, 60], y=[1], edge_features=[60, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[28], ptr=[2])
DataBatch(x=[58, 270], edge_index=[2, 126], y=[1], edge_features=[126, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1],

DataBatch(x=[62, 270], edge_index=[2, 136], y=[1], edge_features=[136, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[62], ptr=[2])
DataBatch(x=[25, 270], edge_index=[2, 56], y=[1], edge_features=[56, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[25], ptr=[2])
DataBatch(x=[25, 270], edge_index=[2, 54], y=[1], edge_features=[54, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[25], ptr=[2])
DataBatch(x=[15, 270], edge_index=[2, 32], y=[1], edge_features=[32, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[15], ptr=[2])
DataBatch(x=[32, 270], edge_index=[2, 72], y=[1], edge_features=[72, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1], batch=[32], ptr=[2])
DataBatch(x=[20, 270], edge_index=[2, 42], y=[1], edge_features=[42, 4], smiles=[1], drug_name=[1], cell_line_name=[1], target=[1, 735], c_size=[1],

everything in the data will be attributed, even for data.batch. this could be incorrect. 

should divide data into two parts:
1. inputs that need to be attributed: feature matrix x, edge features
2. irrelevant inputs: batch, edge index

In [11]:
from captum.attr import Saliency, IntegratedGradients

In [7]:
'''def model_forward(input_mask_d, input_mask_c, data):
# def model_forward(x, target, edge_index, batch):

#     print(x.shape, target.shape, edge_index.shape, batch.shape, edge_feat.shape)
#     print(target)
    output, _ = model(input_mask_d, input_mask_c, data.edge_index, data.batch, data.edge_features)
#     output = model(x, target, edge_index, batch)

    return output

def explain(data, device):
#     data= data.to(device)
    input_mask_drug = torch.ones(data.x.shape[0], data.x.shape[1]).requires_grad_(True).to(device)
    input_mask_cell = torch.ones(data.target.shape[0], data.target.shape[1]).requires_grad_(True).to(device)
    
    print(input_mask_drug.shape)
    print(input_mask_cell.shape)
    ig = IntegratedGradients(model_forward)
    (mask_drug, mask_cell) = ig.attribute((input_mask_drug, input_mask_cell), 
                                          target = 0,
                                          additional_forward_args = (data,),
#                                           additional_forward_args = (data.edge_index, data.batch),
                                          internal_batch_size=data.x.shape[0])
    
    mask_drug = np.abs(mask_drug.cpu().detach().numpy())
    mask_cell = np.abs(mask_cell.cpu().detach().numpy())
    
    if mask_drug.max() > 0:
        mask_drug = mask_drug / mask_drug.max()
        
    if mask_cell.max() > 0:
        mask_cell = mask_drug / mask_cell.max()
    
    return mask_drug, mask_cell
'''

In [12]:
def model_forward(input_mask, data):
# def model_forward(x, target, edge_index, batch):
    
#     print(x.shape, target.shape, edge_index.shape, batch.shape, edge_feat.shape)

#     print(input_mask.shape)
    batch = data.batch
#     batch = batch.type(torch.int64)
#     print(batch)
#     print(data.x.shape, data.target.shape, data.edge_index.shape, batch.shape, data.edge_features.shape)

#     output = model(x, target, edge_index, batch, edge_feat)
    output, _ = model(input_mask, data.edge_index, data.target, batch, data.edge_features)
#     output = model(x, target, edge_index, batch)

    return output

def explain(data, device):
#     data= data.to(device)
    input_mask_drug = torch.ones(data.x.shape[0], data.x.shape[1]).requires_grad_(True).to(device)
#     input_mask_cell = torch.ones(data.target.shape[0], data.target.shape[1]).requires_grad_(True).to(device)

#     print(input_mask_drug.shape)
#     print(data.edge_index.shape)
    ig = IntegratedGradients(model_forward)
    mask_drug = ig.attribute(input_mask_drug, 
                             target = 0,
                             additional_forward_args = (data,)
#                                           additional_forward_args = (data.edge_index, data.batch),
                             , internal_batch_size=data.x.shape[0]
                            )
    
    mask_drug = np.abs(mask_drug.cpu().detach().numpy())
#     mask_cell = np.abs(mask_cell.cpu().detach().numpy())
    
    if mask_drug.max() > 0:
        mask_drug = mask_drug / mask_drug.max()
        
#     if mask_cell.max() > 0:
#         mask_cell = mask_drug / mask_cell.max()
    
    return mask_drug


In [ ]:
# don't run this loop!

'''
# for batch_idx, data in enumerate(test_loader):
for data in test_loader:
#     print(batch_idx)
#     print(type(data))
#     print(data.batch)
    data = data.to(device)
#     mask_drug, mask_cell = explain(data, device)
    mask_drug = explain(data, device)

    print(mask_drug.shape)
#     print(mask_cell)
    
    del data
    torch.cuda.empty_cache()

'''

(28, 270)
(35, 270)
(44, 270)
(34, 270)
(24, 270)
(32, 270)
(58, 270)
(9, 270)
(21, 270)
(34, 270)
(38, 270)
(31, 270)
(25, 270)
(30, 270)
(28, 270)
(26, 270)
(23, 270)
(28, 270)
(21, 270)
(28, 270)
(28, 270)
(32, 270)
(30, 270)
(28, 270)
(34, 270)
(30, 270)
(30, 270)
(28, 270)
(28, 270)
(30, 270)
(24, 270)
(25, 270)
(23, 270)
(32, 270)
(33, 270)
(26, 270)
(37, 270)
(30, 270)
(9, 270)
(28, 270)
(18, 270)
(59, 270)
(28, 270)
(32, 270)
(38, 270)
(28, 270)
(27, 270)
(74, 270)
(32, 270)
(30, 270)
(24, 270)
(28, 270)
(32, 270)
(24, 270)
(25, 270)
(40, 270)
(58, 270)
(28, 270)
(15, 270)
(24, 270)
(37, 270)
(30, 270)
(37, 270)
(33, 270)
(35, 270)
(38, 270)
(15, 270)
(34, 270)
(27, 270)
(34, 270)
(20, 270)
(25, 270)
(38, 270)
(26, 270)
(20, 270)
(38, 270)
(35, 270)
(28, 270)
(37, 270)
(30, 270)
(14, 270)
(30, 270)
(32, 270)
(35, 270)
(25, 270)
(9, 270)
(24, 270)
(61, 270)
(38, 270)
(29, 270)
(28, 270)
(24, 270)
(25, 270)
(28, 270)
(40, 270)
(25, 270)
(35, 270)
(34, 270)
(61, 270)
(58, 270)
(32

In [13]:
# run just one example
data = next(iter(test_loader))
data = data.to(device)
mask_drug = explain(data, device)

In [14]:
mask_drug

array([[0.05736523, 0.09069743, 0.33221221, ..., 0.06113471, 0.03359762,
        0.13531952],
       [0.00502175, 0.12301039, 0.3689001 , ..., 0.07266932, 0.01566642,
        0.29735838],
       [0.07421702, 0.47002287, 0.24962367, ..., 0.02044753, 0.07688424,
        0.6945814 ],
       ...,
       [0.00426597, 0.06841397, 0.09380412, ..., 0.0338943 , 0.00441817,
        0.1862531 ],
       [0.02898184, 0.11281429, 0.062973  , ..., 0.01992493, 0.01448572,
        0.4087947 ],
       [0.01198818, 0.01070309, 0.09515713, ..., 0.01044632, 0.05295419,
        0.13100955]])

In [77]:
data.y

tensor([0.4001])

In [37]:
print(data)
# data[1]

DataBatch(x=[58, 192], edge_index=[2, 126], y=[1], edge_features=[126, 4], target=[1, 735], c_size=[1], batch=[58], ptr=[2])


In [59]:
for i in range(len(data)):
    print(data[i])

Data(x=[58, 192], edge_index=[2, 126], y=[1], edge_features=[126, 4], target=[1, 735], c_size=[1])
Data(x=[30, 192], edge_index=[2, 66], y=[1], edge_features=[66, 4], target=[1, 735], c_size=[1])
Data(x=[20, 192], edge_index=[2, 42], y=[1], edge_features=[42, 4], target=[1, 735], c_size=[1])
Data(x=[34, 192], edge_index=[2, 74], y=[1], edge_features=[74, 4], target=[1, 735], c_size=[1])
Data(x=[26, 192], edge_index=[2, 60], y=[1], edge_features=[60, 4], target=[1, 735], c_size=[1])
Data(x=[32, 192], edge_index=[2, 72], y=[1], edge_features=[72, 4], target=[1, 735], c_size=[1])
Data(x=[33, 192], edge_index=[2, 72], y=[1], edge_features=[72, 4], target=[1, 735], c_size=[1])
Data(x=[28, 192], edge_index=[2, 60], y=[1], edge_features=[60, 4], target=[1, 735], c_size=[1])


In [11]:
x = data.x
x
edge_index = data.edge_index
edge_index

tensor([[    0,     1,     1,  ..., 32814, 32815, 32815],
        [    1,     0,     2,  ..., 32815, 32814, 32810]], device='cuda:0')

In [16]:
data.edge_features.unsqueeze(0)

tensor([[[1., 0., 0., 0.],
         [1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [1., 0., 0., 0.],
         [1., 0., 0., 0.],
         [1., 0., 0., 0.],
         [1., 0., 0., 0.],
         [1., 0., 0., 0.],
         [1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [1., 0., 0., 0.],
         [1., 0., 0., 0.],
         [1., 0., 0., 0.],
         [1., 0., 0., 0.],
         [1., 0., 0., 0.],
         [1., 0., 0., 0.],
         [1., 0., 0., 0.],
         [1., 0., 0., 0.],
         [1., 0., 0., 0.],
         [1., 0., 0., 0.],
         [1., 0., 0., 0.],
         [1., 0., 0., 0.],
         [1., 0., 0., 0.],
         [1., 0., 0., 0.],
         [1., 0., 0., 0.],
         [1., 0., 0., 0.],
         [1., 0., 0., 0.],
         [1., 0., 0., 0.],
         [1., 0., 0., 0.],
         [1., 0., 0., 0.],
         [1., 0., 0., 0.],
         [1., 0., 0., 0.],
         [1., 0., 0., 0.],
 

In [56]:
input_sample = data[7]
input_sample.batch = torch.zeros(1, dtype=int)
# input_sample = input_sample.to(device)

In [57]:
input_sample.edge_index

tensor([[ 0,  1,  1,  1,  2,  2,  2,  3,  3,  3,  4,  4,  5,  5,  6,  7,  7,  7,
          8,  8,  8,  9,  9, 10, 10, 10, 11, 11, 12, 12, 12, 13, 14, 14, 15, 15,
         15, 16, 16, 17, 17, 17, 18, 18, 19, 19, 19, 20, 20, 20, 21, 21, 22, 22,
         23, 24, 25, 25, 26, 27],
        [ 1,  0,  2,  5,  1,  3,  7,  2,  4,  6,  3,  5,  4,  1,  3,  2,  8, 11,
          7,  9, 27,  8, 10,  9, 11, 12, 10,  7, 10, 13, 14, 12, 12, 15, 14, 16,
         25, 15, 17, 16, 18, 22, 17, 19, 18, 20, 24, 19, 21, 23, 20, 22, 21, 17,
         20, 19, 15, 26, 25,  8]])

In [76]:
input_sample

Data(x=[28, 192], edge_index=[2, 60], y=[1], edge_features=[60, 4], target=[1, 735], c_size=[1], batch=[1])

In [48]:
mask_drug, mask_cell = explain(input_sample, device)

RuntimeError: Sizes of tensors must match except in dimension 1. Got 4 and 2 in dimension 0 (The offending index is 1)

In [75]:
# del data
torch.cuda.empty_cache()

In [16]:
device

device(type='cuda', index=0)

In [ ]:
import numpy as 